#example with encrypted secret using ksops
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-db
  namespace: cloudnative-pg
spec:
  instances: 1

  superuserSecret:
    name: test-db-superuser

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: test-db-app

  storage:
    size: 2Gi
    storageClass: local-path


# apiVersion: postgresql.cnpg.io/v1
# kind: Cluster
# metadata:
#   name: test-db
#   namespace: cloudnative-pg
# spec:
#   instances: 1

#   storage:
#     size: 2Gi
#     storageClass: local-path

#   monitoring:
#     enablePodMonitor: true

#example using resources limits
# cluster:
#   name: "postgres-cluster"

# instances: 3

# resources:
#   limits:
#     cpu: 500m
#     memory: 1Gi
#   requests:
#     cpu: 100m
#     memory: 1Gi

# storage:
#   size: 8Gi
#   accessMode: ReadWriteOnce

# backup:
#   enabled: false
