apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-cloudnative-pg
  namespace: argocd
spec:
  project: default

  sources:
    # Operator (Helm)
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: v0.27.1
      helm:
        skipSchemaValidation: true
        valueFiles:
          - $values/kubernetes/infrastructure/cloudnative-pg/values.yaml

    # Values reference
    - repoURL: https://github.com/MosheAzraf/pi-cluster.git
      targetRevision: main
      ref: values

    # Clusters + Secrets (Kustomize root)
    - repoURL: https://github.com/MosheAzraf/pi-cluster.git
      targetRevision: main
      path: kubernetes/infrastructure/cloudnative-pg

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
