apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:yrwreRI=,iv:jUfG74n3D44F++7qy6QwM1l46zqZJwRBd+JhwiAeGBU=,tag:/9nVUGAlz5xqJFlXZBvNHg==,type:str]
    admin-password: ENC[AES256_GCM,data:R+52cjvFKzuAB1E=,iv:E78L8eDq2cD0P74jSGfk45a96uNAXtE6xrzpKCvUI6I=,tag:/mbtvq2C8CILvUfcvBaEAQ==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSazdsQ1lFOWlaUDQraGh1
            RzBJWWdiaVhreHpMTGpjcHVlb1F3Q1ltcVE4CndMUGN4L282Mk54TGF0and1UmFt
            amVMVnJucXcweTZqQTRsU29SWDVabEUKLS0tIDN4RkllT1R6bi9SWStDUDFaL1Rv
            TjFFbFFBbUZ3YWdUaFlnL3Z1eFR5NkUKiJOvCv6hmvIbsXw5IrDjym+NgoWyJhRJ
            1ZmTXM7TEuhMa3FYLr6QGq72ff1jwQPg1QKbddnlSkvGLWdJTnzoKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T08:44:37Z"
    mac: ENC[AES256_GCM,data:+DcZmexWc48LN1QibxQ2oDQLoNAQBqn1iRtoUcF530lIXN/DSPwNaetnLf3RBjp5noIkmnnAtA/EoFZwMsZQDJhNBVQF1ToxtGcuQVyqPKOuV2YwiBRb5fzrNL8eO8G5RmToqBuhhHPNSigH+JZOLB0l/dp5y3x3rBQ7kG/8vdo=,iv:3LBnGZQ9mexqMmkN7019ScVmd+YJFNpAudh0v2r3zjo=,tag:Uq4iqKk57ZKArTZeoRPXjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
