apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:hGBlBaC++NPe/QVh22SleSe+VhIi1eIDyth/aHJpV3DQl3jLJNQkBRC3bicZFLg6mQSSpI+mhdnSzCFAPahMzteoJa0TLUN+Pl7XCn+ykwtG78WZwDrMwOXElgEw,iv:kgkleq+8sLua/rQVa33I/dysihMdIbqts81hp/CisMo=,tag:gmeEGHZ6HnDFPPkJ+eaJHw==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bWJpLzdBR3JybkNXVnBa
            UlcrS3VPbFNLNHpsQjdVbTEyZnNwSzd4ZkJrCktCK1VGTGJIdUs0RWZVNjdiS3lX
            a1ltQSt6cXFzMVErbjVkTkF2dzQwa1UKLS0tIHBqSjVZMUtYUkMxUXV2bnlpZURu
            UlIyNWl6VWZiWEJjSkJjS0FVSDBHZ0UK1ybdLzJGTxfNCCO0qQDkAIVCLu3TiLFk
            SwpNm/OlvQN02beK+Qh+ui5nT2Vb8ZMZV3VvPpn3wQEDEZD7F3E8pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T15:18:33Z"
    mac: ENC[AES256_GCM,data:e/MIfqO2cuILNRC17NnhbEo7AG8ElgXfSB22NM8RSkg3VWcuYlimlLM+VydC+FABgzvetkU9QW8JHYcbdKoUEI1yhfCH9Dp4RNllNFMq8pEzpR8rLDvSNPtuYdcKRch/VXTbEcAgUN5OyjV+4jEkUCESXIbqma37/ZvU+fDA2fU=,iv:4EEg6oxbzSAL28ADd8/eJGKAQ1HZwfV11Fsbnh4ctG8=,tag:sBdqFstE/d5+oOuflpY8Ew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
