apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:+JDtCwvBuf7xP6CYaW4FF5euVn7QqbBnRUEfWbWVcAxfZ2lU21fiCN4pRHKXVdbWfNRZYCvwchDyM0vAHvL+Yz0thvxbvayxfkswPG/RwK1aKP7tEpCpKvfZJLQS,iv:M6UYZ0Hl7F2ZUxyP2C1xTEu0rMYpOvQR1tqEj4NCaig=,tag:UHiY33/lpRhauIwa7x7cZA==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bWJpLzdBR3JybkNXVnBa
            UlcrS3VPbFNLNHpsQjdVbTEyZnNwSzd4ZkJrCktCK1VGTGJIdUs0RWZVNjdiS3lX
            a1ltQSt6cXFzMVErbjVkTkF2dzQwa1UKLS0tIHBqSjVZMUtYUkMxUXV2bnlpZURu
            UlIyNWl6VWZiWEJjSkJjS0FVSDBHZ0UK1ybdLzJGTxfNCCO0qQDkAIVCLu3TiLFk
            SwpNm/OlvQN02beK+Qh+ui5nT2Vb8ZMZV3VvPpn3wQEDEZD7F3E8pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T14:22:55Z"
    mac: ENC[AES256_GCM,data:wky6sNtUKBUjtXxpFlHsaQSoJqP3aQsj29zrl0eBmca6AcMsB/AAUlcVT/AY89+f9l0yIvkIPn4uvAjBcH33NpswzlYRUKegHKgUXbXaFbA8yOZfmQrQuPGJ2sK8SxrJFmAO3nOVuk2mjO7c/qdgGrBxBbh5j8lEn4O43DAOHu8=,iv:SuYRLBSje7a2ORY08ZOvzxPWbNcBYrFoBVDxSBHl1NM=,tag:swLa1uzw3H8XC5KzEsxjBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
