apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:yJ95NpVJyOTrb2lpMSjUd0BBS9XOY+oOKO4GZi+tH/IyPPm/oXT17awDQ+bg9TdAor2RoQma+vrJgG311F+Iq0kCb4Fu7BfcwZpru5nvLU5v6TdNufN5ilE1OLxS,iv:D2XgLgI27ce/IMJk839RwZrpKpTpooCMzXfw0t5l4XU=,tag:iRDTrxJ6Q5DA56RY2NTXow==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bWJpLzdBR3JybkNXVnBa
            UlcrS3VPbFNLNHpsQjdVbTEyZnNwSzd4ZkJrCktCK1VGTGJIdUs0RWZVNjdiS3lX
            a1ltQSt6cXFzMVErbjVkTkF2dzQwa1UKLS0tIHBqSjVZMUtYUkMxUXV2bnlpZURu
            UlIyNWl6VWZiWEJjSkJjS0FVSDBHZ0UK1ybdLzJGTxfNCCO0qQDkAIVCLu3TiLFk
            SwpNm/OlvQN02beK+Qh+ui5nT2Vb8ZMZV3VvPpn3wQEDEZD7F3E8pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T15:55:13Z"
    mac: ENC[AES256_GCM,data:BZSrc8g4K5wN179rPdN+gANbsTzp38XnZ6My7mUfc5ozBa7exbUAiXMkeKUgEZTpqMUfkvUBi5ZoU0L569R8GFK2ZFo+KHMkC8GkJZm1pOYlxozF/8aWogo0fopUlhga0IbczZ/YcjxKK/D8/6wPDbw/398yUr1JY0ApGQMe3hw=,iv:d6bmMKgVq9//Coms94ileQsbpq9nNuiBcO2Z4xPqkUU=,tag:uYTOiH4fCO5EXpB98Sw0kA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
