#it is recommended not to expose the db outside of the cluster and let an 
#internal app access it. 
#this load balancer is only for testing.
#an example for internal connection can be:
#test-db-rw.cloudnative-pg.svc.cluster.local


apiVersion: v1
kind: Service
metadata:
  name: test-db-external
  namespace: cloudnative-pg
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.205
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: test-db
    cnpg.io/instanceRole: primary
