apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cloudnative-pg
spec:
  instances: 2

  superuserSecret:
    name: postgres-superuser

  bootstrap:
    initdb:
      database: postgres
      owner: postgres

  storage:
    size: 10Gi
    storageClass: local-path

  managed:
    roles:
      - name: linkding
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: linkding-db-secret


# apiVersion: postgresql.cnpg.io/v1
# kind: Cluster
# metadata:
#   name: test-db
#   namespace: cloudnative-pg
# spec:
#   instances: 1

#   storage:
#     size: 2Gi
#     storageClass: local-path

#   monitoring:
#     enablePodMonitor: true

#example using resources limits
# cluster:
#   name: "postgres-cluster"

# instances: 3

# resources:
#   limits:
#     cpu: 500m
#     memory: 1Gi
#   requests:
#     cpu: 100m
#     memory: 1Gi

# storage:
#   size: 8Gi
#   accessMode: ReadWriteOnce

# backup:
#   enabled: false
