apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-tls
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MosheAzraf/pi-cluster
    targetRevision: main
    path: kubernetes/apps/test-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
