cronjob:
  schedule: "*/3 * * * *"
  # schedule: "0 */6 * * *"

renovate:
  config: |
    {
      "repositories": ["MosheAzraf/pi-cluster"]
    }

existingSecret: renovate-secret

env:
  RENOVATE_PLATFORM: "github"
  LOG_LEVEL: "debug"