cronjob:
  schedule: "0 0 * * *"

renovate:
  config: |
    {
      "repositories": ["MosheAzraf/pi-cluster"]
    }

existingSecret: renovate-secret

env:
  RENOVATE_PLATFORM: "github"
  LOG_LEVEL: "debug"