apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prometheus.home.lab`)
      services:
        - name: monitoring-prometheus-kube-prometheus

          port: 9090
  tls:
    secretName: prometheus-tls
