apiVersion: v1
kind: Secret
metadata:
    name: linkding-env
    namespace: linkding
type: Opaque
stringData:
    LD_DB_ENGINE: ENC[AES256_GCM,data:vEG2EhzibJw=,iv:FdyTzJxg9xdDlAoAS81TriiNJsaXzr0sfc7meFNc6T4=,tag:EgaWOqi//vCjcTfiGuh2uQ==,type:str]
    LD_DB_DATABASE: ENC[AES256_GCM,data:ckrpSWIxCrY=,iv:ihdYWbhKE2lQ5yBN/YSXev6U7Rlcq3OVDzykeR0ueoM=,tag:vF8DTy2V6GLUT5HlzY0uMw==,type:str]
    LD_DB_USER: ENC[AES256_GCM,data:xTz8+d1z6CM=,iv:OGw8YATx3hrbF568u3AAjVfsCh22hQor+KkFU32IkXk=,tag:l3l24R91feQnOOG071BgNQ==,type:str]
    LD_DB_PASSWORD: ENC[AES256_GCM,data:tJbE8x7Y6H4=,iv:ZO9PSWLLgDF6N4ma5XaOcGc+Q87o+Ed0USamlUS4Ans=,tag:ryKWsNSzC09uWVZoBQap3w==,type:str]
    LD_DB_HOST: ENC[AES256_GCM,data:ovwytDwXZ1hdZvw8KT2xQSMhJuSPPpcij3jU6SSclGhyBgSgwXoQIkMviiA=,iv:P3sxlEo1U5hhGK8HPCSl936mPItcYAHZHbPGGiVdyZU=,tag:fT08UQJqfMZU0STf7IdKcA==,type:str]
    LD_DB_PORT: ENC[AES256_GCM,data:hUPg7Q==,iv:7ygOuwypycHmI6Mn3pzJaioRBaBPqA2/Y6ykYnpBIPk=,tag:pxSi9gMvmCIPNW7ii5/Npg==,type:str]
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:/veXDjs=,iv:S3/iEJ8m/XQJnWNpk1xyf65itc/u9ULyFfkEl3aJC8o=,tag:+/S5ekTQbuNdRMME3D6KIg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:pQBzZTlmZTZu,iv:2flIiULgh7cvkyxjYTc/agR130dlMNhJT0JHEZ3p9mc=,tag:Sfat4A2HYiVYhCZP3h3k+g==,type:str]
    LD_SUPERUSER_EMAIL: ENC[AES256_GCM,data:jvAHk8lxJ+7fbJ/UOjdgEFN5R5ku,iv:tw8IL/lXe223/MV8cOHUZSJU0Ste49W3HGrGlWJHJdM=,tag:uJxhRLkvJV5QGQd6CtLYAg==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNm9KcW1qc0FyWmQzS1JW
            VnV4NVE4NkRmQkkrdUl1QzFBdVQxQXRqc2pvCkJFNDBPK28wS3l2WFN2NjhDd2pa
            LzdBSkxoQ0JHUUxGb3E4NEN0eEt6dFEKLS0tIHB1YkNpcFBpekdMMURybHpsK25s
            OGkvaFozcUdacGNjeFJ0eTBLa053eXMKv5DE+pZsL012cTFSTegVe0+97MKaViN9
            VUwA9PtBDcc+8a/FLkblC1Lck3K/zOOdtDVO9h+Ru+V0tadn0H+SfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T17:29:28Z"
    mac: ENC[AES256_GCM,data:Kfl8MwWHdf/UKo91G2bwJNaLLFGYxfhkeppC/Uk6lEy6i9XRIi3Fl+jt8sxlrqfpqYCMqwoFhmeV94+gE2zAaolWWBfTlsj46vhJWJUYD6uDM6k56kxc7tpY8kypo3rmiVMUi0MbxOJCVLPzz/d/r+Eoi0sej7ao9T4ge35f99E=,iv:LyCnYvPrA4PkhpKxbY37A+b9aIrp6uKYttFUGiOV4JA=,tag:to0tlQ6CScnGvZ/z0HmssQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
