apiVersion: v1
kind: Secret
metadata:
    name: linkding-env
    namespace: linkding
type: Opaque
stringData:
    LD_DB_ENGINE: ENC[AES256_GCM,data:vEG2EhzibJw=,iv:FdyTzJxg9xdDlAoAS81TriiNJsaXzr0sfc7meFNc6T4=,tag:EgaWOqi//vCjcTfiGuh2uQ==,type:str]
    LD_DB_DATABASE: ENC[AES256_GCM,data:ckrpSWIxCrY=,iv:ihdYWbhKE2lQ5yBN/YSXev6U7Rlcq3OVDzykeR0ueoM=,tag:vF8DTy2V6GLUT5HlzY0uMw==,type:str]
    LD_DB_USER: ENC[AES256_GCM,data:xTz8+d1z6CM=,iv:OGw8YATx3hrbF568u3AAjVfsCh22hQor+KkFU32IkXk=,tag:l3l24R91feQnOOG071BgNQ==,type:str]
    LD_DB_PASSWORD: ENC[AES256_GCM,data:tJbE8x7Y6H4=,iv:ZO9PSWLLgDF6N4ma5XaOcGc+Q87o+Ed0USamlUS4Ans=,tag:ryKWsNSzC09uWVZoBQap3w==,type:str]
    LD_DB_HOST: ENC[AES256_GCM,data:ovwytDwXZ1hdZvw8KT2xQSMhJuSPPpcij3jU6SSclGhyBgSgwXoQIkMviiA=,iv:P3sxlEo1U5hhGK8HPCSl936mPItcYAHZHbPGGiVdyZU=,tag:fT08UQJqfMZU0STf7IdKcA==,type:str]
    LD_DB_PORT: ENC[AES256_GCM,data:hUPg7Q==,iv:7ygOuwypycHmI6Mn3pzJaioRBaBPqA2/Y6ykYnpBIPk=,tag:pxSi9gMvmCIPNW7ii5/Npg==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNm9KcW1qc0FyWmQzS1JW
            VnV4NVE4NkRmQkkrdUl1QzFBdVQxQXRqc2pvCkJFNDBPK28wS3l2WFN2NjhDd2pa
            LzdBSkxoQ0JHUUxGb3E4NEN0eEt6dFEKLS0tIHB1YkNpcFBpekdMMURybHpsK25s
            OGkvaFozcUdacGNjeFJ0eTBLa053eXMKv5DE+pZsL012cTFSTegVe0+97MKaViN9
            VUwA9PtBDcc+8a/FLkblC1Lck3K/zOOdtDVO9h+Ru+V0tadn0H+SfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T17:07:34Z"
    mac: ENC[AES256_GCM,data:m7Ppj240nxOjIYkaE/9DHyv9+fEqVi+zmE5oJsp1lZumFQIDcPin3DL/eINYfQ6U9cdmzyRSwAp43OH7ev/+arpnp0CAZJUR8xym2yVAPcbmBMEnNXVGhkQblosqwffw8fd6U0OCZtiIl/HkhhmF6O47/YvegJGQIUiTB1NCtYM=,iv:V7QmloaQa5r0DGsNHEugPXy3TFZX6xMUsusp15RfkIo=,tag:HxVgQK6EpodzA0y5I+DFjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
