apiVersion: v1
kind: Secret
metadata:
    name: linkding-db-secret
    namespace: cloudnative-pg
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:zoYPzqowBtg=,iv:f0S/r3DAmMyoTvjMcFYFh+QuTnALQyRQQiQKQIRd7LY=,tag:0xxblQfy2p1DzrT/nwYaMg==,type:str]
    password: ENC[AES256_GCM,data:Lleqex2RNQk=,iv:k3/7MgUWwETuZxsTcQP8qs0l1eZPzPLLY0K4jA26MAw=,tag:hKfN2xOOKnyKogXVo9Yy/Q==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWjhzSlcwMzR5d3Q1Rk5F
            MFZGT0ZFdVoza3BSUCtQQlp6VWJUSmhFYmlZCmZ1SlpGVFM2Mi9HZ3RWbEE3VFZD
            Zi8xY3dpc0tjTDU1QVgyTU1Wcy9BbXcKLS0tIGNleFdVc1pYdGJUNmw2Um1nenpD
            Q25jKy8rcmVHdW9waWJvZ254SmVoTGsKACDGbcbD3sNrMfK4t6tQhmH8TeOfaRAe
            h9QO7HeTMRx1u4+iUuMFKmY8OtogMuCFjjXztjxyNIw4qlIXIXzxOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T15:38:10Z"
    mac: ENC[AES256_GCM,data:eyHC//BfeHsx6/n8jYyK0mzWsOoA2ksKLctA/f19wWUkd5rV3M0Wm8DAnM/CQ7RRgWZUDPGANnt+oome5vtFakmOxzWyhBh2LDftTOv6La0+CMfhs/i0KpmhxnGxid5HYJ3ttcWQHf1euF+RtEe47fa0t3UPJHSTDVGVGYY+CuI=,iv:v8cth09b/mP0PnRYW7Q/8exPTazmxeIZcqRNv3o1pyI=,tag:F8GSYiEWE0j+9QnldLcGOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
