apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
    namespace: cloudnative-pg
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:B5TjJdu3oAA=,iv:Nfx19gaTwQCMJDaoq4il1jWYPHHdWHXBpgsk3PhozbM=,tag:DGp3N3l5D364MNI4yfF+2w==,type:str]
    password: ENC[AES256_GCM,data:L2Kmta9c7HWA1fUW9wg=,iv:fKLv77M+sYhGFwkTovkHL+vAoXbkQAiZzmoQfGV45VA=,tag:upWx/yAHk9Oy/f0IZHtREA==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVzdsdGhSVG1ndGEzditT
            Y0NibUxMSFJQSkFmc3hQOUM2M0QyRER4aVNrClJTdDlRc0gzVnlCaGh0KzI4cGQz
            V3VsR1hrM2lIaUFQaTVkUEF1SFZVRTgKLS0tIHp5TDgxSmpHU3gyTzhHLzkyNTZz
            MnAxbGNRejVFZ2lYd2V3WHd3R3g4d00KeWBPo2dta86/bSG/xRS+AF1tI9tl/JCG
            IUgLaQ+h55W7P3W4lDNUB30n9WJOtZRB+QzducKjN+K0+Bf8Jugg1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T16:04:48Z"
    mac: ENC[AES256_GCM,data:fjDNZ5xH5rFEa7vCO363vsf6Qnr+SSnZTQPimaMnqJqo1wEHMjD8Ae39zRy8F+cA0xeecr+ktL9tAvP4WDGg8XgIk3VWuG0+J9LzQGzgHfgLcOtgPgBQQDIYRHBSynrtn4Yb2RRTv+ymCYvzv0LM9MOYkKOITGhV4FUfpyEIj3c=,iv:clH89FM2vVh85S+O5zYldgHgqHiI1V9NX9waPNcQjmY=,tag:jMjjiKbTAWCDrUL+dcx1OQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
