apiVersion: v1
kind: Secret
metadata:
    name: test-db-superuser
    namespace: cloudnative-pg
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:B5TjJdu3oAA=,iv:Nfx19gaTwQCMJDaoq4il1jWYPHHdWHXBpgsk3PhozbM=,tag:DGp3N3l5D364MNI4yfF+2w==,type:str]
    password: ENC[AES256_GCM,data:L2Kmta9c7HWA1fUW9wg=,iv:fKLv77M+sYhGFwkTovkHL+vAoXbkQAiZzmoQfGV45VA=,tag:upWx/yAHk9Oy/f0IZHtREA==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVzdsdGhSVG1ndGEzditT
            Y0NibUxMSFJQSkFmc3hQOUM2M0QyRER4aVNrClJTdDlRc0gzVnlCaGh0KzI4cGQz
            V3VsR1hrM2lIaUFQaTVkUEF1SFZVRTgKLS0tIHp5TDgxSmpHU3gyTzhHLzkyNTZz
            MnAxbGNRejVFZ2lYd2V3WHd3R3g4d00KeWBPo2dta86/bSG/xRS+AF1tI9tl/JCG
            IUgLaQ+h55W7P3W4lDNUB30n9WJOtZRB+QzducKjN+K0+Bf8Jugg1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T14:49:17Z"
    mac: ENC[AES256_GCM,data:Ql6LyEu7zDw89tN23pXby8pCdTc3f6AWabrX5McaK2B6O+X9s/geF/h1Af4O4zkB/Jm07pwzth68Q+/acYWz1TBdeFMx09qFz1/xNhJ/tXhjbwModv2To8HUW4Jet6uqG9RdbFPcR6U+D748QI7DeHfQdtbPjbsVyRVaA75dfv4=,iv:GwVu3L6jmBhKE2msViwpZIoJzbwl2/ymcU8bw4V2Eo0=,tag:p9f0DRy38OM/MxQs4PFDAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
