apiVersion: v1
kind: Secret
metadata:
    name: test-db-superuser
    namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:FG7IqldNrxM=,iv:oehCbsq82hnX2EuHr23JZsJ3xNJ4EQKczNkFvY0Ryp0=,tag:aLtMRvUf5gIpZ+BGchpURA==,type:str]
    password: ENC[AES256_GCM,data:5gFV21UQm9D6FOsZLTc=,iv:kwvuXia8MnzKPWs7l/TtnOqqOge4CtI2EdW2YE3reRM=,tag:W9YpDdSd3XcbbslR98x7kw==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVzdsdGhSVG1ndGEzditT
            Y0NibUxMSFJQSkFmc3hQOUM2M0QyRER4aVNrClJTdDlRc0gzVnlCaGh0KzI4cGQz
            V3VsR1hrM2lIaUFQaTVkUEF1SFZVRTgKLS0tIHp5TDgxSmpHU3gyTzhHLzkyNTZz
            MnAxbGNRejVFZ2lYd2V3WHd3R3g4d00KeWBPo2dta86/bSG/xRS+AF1tI9tl/JCG
            IUgLaQ+h55W7P3W4lDNUB30n9WJOtZRB+QzducKjN+K0+Bf8Jugg1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T11:41:49Z"
    mac: ENC[AES256_GCM,data:fHFSMF2RJIZoP6bWk2aQh22gPT4YbRdxWuNJKhp/d1wqRaxeQslblBqcLbifmus2AxhCp3jGHlfmNNhgbbFNsS/Iu75eJOyBj41xZhGx1GhyIA9b78SR39mezkG9EPMhr1Sf2Cqo51IMgYVDKeAeUyQtpl9+TIQRzKEx6h5bZXQ=,iv:TwmfDZnqD/wTgdyN+8eSX0QqgaE5YVvlZEMTlg/zmo0=,tag:ARK/gAgUCGjAzHp8hchxRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
