apiVersion: v1
kind: Secret
metadata:
    name: test-db-superuser
    namespace: cloudnative-pg
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:FG7IqldNrxM=,iv:oehCbsq82hnX2EuHr23JZsJ3xNJ4EQKczNkFvY0Ryp0=,tag:aLtMRvUf5gIpZ+BGchpURA==,type:str]
    password: ENC[AES256_GCM,data:5gFV21UQm9D6FOsZLTc=,iv:kwvuXia8MnzKPWs7l/TtnOqqOge4CtI2EdW2YE3reRM=,tag:W9YpDdSd3XcbbslR98x7kw==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVzdsdGhSVG1ndGEzditT
            Y0NibUxMSFJQSkFmc3hQOUM2M0QyRER4aVNrClJTdDlRc0gzVnlCaGh0KzI4cGQz
            V3VsR1hrM2lIaUFQaTVkUEF1SFZVRTgKLS0tIHp5TDgxSmpHU3gyTzhHLzkyNTZz
            MnAxbGNRejVFZ2lYd2V3WHd3R3g4d00KeWBPo2dta86/bSG/xRS+AF1tI9tl/JCG
            IUgLaQ+h55W7P3W4lDNUB30n9WJOtZRB+QzducKjN+K0+Bf8Jugg1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T12:21:38Z"
    mac: ENC[AES256_GCM,data:IPCFVza2TjqKf6KJY+DTZ00xwS9GjV2ksI9NLxaZIgUBBH13/yLfKh2usI7csvb+wIXR2oHD3qcPio3MmkxctFmK/ubDwxViKDrKmRuIw1aV2Cax9rhzXitxF63TK+F+bfiOlOFDP36I2GTqnHBkam42J5n9VkcIusMJY6r0ins=,iv:ZKOqJPAVheJ5uARaKxmdhzpMgBMYxfG9bYxpY1lnWG8=,tag:5O9kVtRZ0LvWU3eYeJsEqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
