apiVersion: v1
kind: Secret
metadata:
    name: test-db-app
    namespace: cloudnative-pg
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mEeZ,iv:OMF556Zkzo8jWaHUOvjd1XecvOgMK+2Vrwb55xmlKUY=,tag:aGfy6xgXfOUvXJa5OrGCzg==,type:str]
    password: ENC[AES256_GCM,data:PWbtBlRUy8zhFA0=,iv:ATIYWv50DnaFbSYRyufn4ZZLl5Xxp1+VvUwDskqs3Uo=,tag:PK4R0NkP3XLMDVpsAn0uFA==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc0kyU3h2aGpJM1pubEFu
            T2dZQWpyUERubUpiUWIrdXFBZXJ2amJRNFZNClo3dGJnS0paNUR1L0tPMk4zQk55
            T1BFNWxaNWErNTlLWUs3L09wQXZaVkkKLS0tIGJxV2wyREQvZG5VamFjVkRRVEE3
            aElMeWlaWGNieHlqdVJVYmlGcmQwbzQKqSSBMg6NmYi9rnSQrBw3Fw7G0kc5OCjm
            B866vwwGeuFGbdZCI7SCqjO5047u3QvoS9bES7LSvh3ITJ07WTgkyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T14:50:21Z"
    mac: ENC[AES256_GCM,data:SE4DJ9VSooIE2H9fabLxmNE5OserulbyLml3zQXKZxpuyTnX4GadX16phFCKt7PKX0ihREZ57SnJvE/AEQk8s9hh6aq00+a+noJy7pPXksVPovfvIX3EqSf9gH3eUI/mbZcAxU7QBlcUghj/bZhbt4R/QkX31AOkwvWeX+OFrss=,iv:vR8x0dEqkYRy1fhQ5xY6+678CvFtTtenzY9YZjsni80=,tag:tXslGswzFZpx4q/gi5F1xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
