apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    #ENC[AES256_GCM,data:xfxVEblSRMSffgggTA==,iv:83wXDVykj1yKMEF7+oSgGe3RWcZFTw6wSC3ZvqnLYZw=,tag:GHiKcI6rYXi2NFiy4TmqFQ==,type:comment]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:Yx9IqCw=,iv:D9cKAcDLCCCEGDv9BN8Pb5BJlBgYH3D3L0kUakp2XEk=,tag:+FNtJN9vun2yQp92ECMI2w==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:QnwRqtDm/Gk=,iv:+BJm+QmHT1UP/WWOQkBpV1U4O6ptuuDjis4at1zo5jM=,tag:T4FcdlB8BNULhQsel8P6Pg==,type:str]
    #ENC[AES256_GCM,data:294WWS2ZZdbIF9Pf7Brbww==,iv:BfhKbGkUXd4FYsDHUXDvEDgIGoaqvq9OcKNOlqW2ZPE=,tag:XqRYCG3XMxI687juh8Ho6w==,type:comment]
    HOMEPAGE_VAR_OMV_USERNAME: ENC[AES256_GCM,data:RpcIt0w=,iv:C4DQS4nACZpRdmg+0Y0WHpf37xG/UsfVcet61Br5hHA=,tag:Nk4tTXuLkhWg/FWXbG5grQ==,type:str]
    HOMEPAGE_VAR_OMV_PASSWORD: ENC[AES256_GCM,data:oOQ80no=,iv:K878c1GorxwmlaO4rPchSGfrAx68OqQaK5gQrknFF2k=,tag:tDmekkvLsoByTEaw/jSsiA==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dzZUWGxIWG1EY3RIYlB4
            ckx4ZGk4bmp1dmVLQkQ5cCtBL3hFdk9JL2lFCjkxaXVsVk95UTJkSlZYUmpleWRq
            OHcxSlpuWno3MEFpTlFuYXdxMy9KSkUKLS0tIEp0WEUyWHl6ZmNSNkxSMitpNU5x
            Vjk4ODgrT2ZrVE1JZFVoTGk4Y2F3UkEKAJoz+WEonjS+0Lg+gYCuoAXDfC2Cp6it
            0djaBN7APsrCaY5kSgoiL9X4an1NVKYHnZfKqVD2hocxu7aTbuyZtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T16:55:49Z"
    mac: ENC[AES256_GCM,data:7rfN8z2Os1Aa9MpsNA+yVf6fwpxGbN7S6yS/ly6aALgHnBLwkL6jmq9ZWPmGBSpCgx93+unfCrfDMVVpYAFngT/ha4yE9Sg84N2+Es1y0l/2lPFJC55NaMJn9YK7GBMZReIAQsqcZKpe+L7QX2ZKGK79OzasbI/Vv6c9cS8bRzk=,iv:E5Sk10+spDPaZwi0HOSn57LL16jRyaVEvQ1QxZhyVXQ=,tag:AJMJhvnTl3DgjSaXqULQZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
