apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    #ENC[AES256_GCM,data:xfxVEblSRMSffgggTA==,iv:83wXDVykj1yKMEF7+oSgGe3RWcZFTw6wSC3ZvqnLYZw=,tag:GHiKcI6rYXi2NFiy4TmqFQ==,type:comment]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:Yx9IqCw=,iv:D9cKAcDLCCCEGDv9BN8Pb5BJlBgYH3D3L0kUakp2XEk=,tag:+FNtJN9vun2yQp92ECMI2w==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:QnwRqtDm/Gk=,iv:+BJm+QmHT1UP/WWOQkBpV1U4O6ptuuDjis4at1zo5jM=,tag:T4FcdlB8BNULhQsel8P6Pg==,type:str]
    #ENC[AES256_GCM,data:294WWS2ZZdbIF9Pf7Brbww==,iv:BfhKbGkUXd4FYsDHUXDvEDgIGoaqvq9OcKNOlqW2ZPE=,tag:XqRYCG3XMxI687juh8Ho6w==,type:comment]
    HOMEPAGE_VAR_OMV_USERNAME: ENC[AES256_GCM,data:RpcIt0w=,iv:C4DQS4nACZpRdmg+0Y0WHpf37xG/UsfVcet61Br5hHA=,tag:Nk4tTXuLkhWg/FWXbG5grQ==,type:str]
    HOMEPAGE_VAR_OMV_PASSWORD: ENC[AES256_GCM,data:oOQ80no=,iv:K878c1GorxwmlaO4rPchSGfrAx68OqQaK5gQrknFF2k=,tag:tDmekkvLsoByTEaw/jSsiA==,type:str]
    #ENC[AES256_GCM,data:V4WmtzFCOA==,iv:t6AXOWEUGn8VxZdQbunnHspg3ZKrX6PaPT5vH3L8HQ4=,tag:7Sy7sHbTZyPIslkp31Lliw==,type:comment]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:024tyoM=,iv:s57GynVprDhiktkjFQ8vyyhz8hZfLxVZBn9Dam52kBs=,tag:IKZpxqwBNNG0z7m0+q/26Q==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:nuUu7SvrnswbS/K1,iv:w4PxL5PEN3UzaV3K7WPYQfGLiDzKJ2UG2wMdFnsmFvI=,tag:r1ac55GvRMCRh39VfXihKA==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dzZUWGxIWG1EY3RIYlB4
            ckx4ZGk4bmp1dmVLQkQ5cCtBL3hFdk9JL2lFCjkxaXVsVk95UTJkSlZYUmpleWRq
            OHcxSlpuWno3MEFpTlFuYXdxMy9KSkUKLS0tIEp0WEUyWHl6ZmNSNkxSMitpNU5x
            Vjk4ODgrT2ZrVE1JZFVoTGk4Y2F3UkEKAJoz+WEonjS+0Lg+gYCuoAXDfC2Cp6it
            0djaBN7APsrCaY5kSgoiL9X4an1NVKYHnZfKqVD2hocxu7aTbuyZtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:24:07Z"
    mac: ENC[AES256_GCM,data:5Mw8yXwoM7swtfoZbqQALMikmkPqNUzJl6jU6zHAhzC3cK2AfpSdgH7mbYoZsMoCMKJnxbrnonEQrBMe7V/omlEdFNkowPa8BWnrhAKMmAaYL2njcVHxZPuTjkN+MPctBXj/awZ4Xvi5tSO9g5HW11TAHdKN7PolYHMZXrTCLxs=,iv:yZv+ykk7WGuIXhsMKKQ2DcIxl21GwlDS1YR7QwWNnxo=,tag:HavEdFyNsMQ7YmartglKHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
