apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    #ENC[AES256_GCM,data:xfxVEblSRMSffgggTA==,iv:83wXDVykj1yKMEF7+oSgGe3RWcZFTw6wSC3ZvqnLYZw=,tag:GHiKcI6rYXi2NFiy4TmqFQ==,type:comment]
    ADGUARD_USERNAME: ENC[AES256_GCM,data:ZJrRQNU=,iv:cEl5WjQEP36KsO72MoWQ4pBnxngpgu23m+/nPTmj3iY=,tag:cY7fYAjrgyo6wA8WbxDXkw==,type:str]
    ADGUARD_PASSWORD: ENC[AES256_GCM,data:Z0aSwm5RKHI=,iv:LJy90HpqjrkuUmgmzL12peVtTYJTnmDeKIpbw9Fqp1c=,tag:TutjqFU/73wYuzat8jwGJQ==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dzZUWGxIWG1EY3RIYlB4
            ckx4ZGk4bmp1dmVLQkQ5cCtBL3hFdk9JL2lFCjkxaXVsVk95UTJkSlZYUmpleWRq
            OHcxSlpuWno3MEFpTlFuYXdxMy9KSkUKLS0tIEp0WEUyWHl6ZmNSNkxSMitpNU5x
            Vjk4ODgrT2ZrVE1JZFVoTGk4Y2F3UkEKAJoz+WEonjS+0Lg+gYCuoAXDfC2Cp6it
            0djaBN7APsrCaY5kSgoiL9X4an1NVKYHnZfKqVD2hocxu7aTbuyZtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T16:08:31Z"
    mac: ENC[AES256_GCM,data:OvSYj3n+9FQMxxRAlZP+bynfCC1PB0asgHhNbTXIj5VPv9KfORXg5aDhZOKBikL3gWW5z8L7Et67wHQcTdw4J5f9GklAGkfm128MsFNq0tlONibrlCdaaVH1sSes9MivrR8y1mCNv08n0TPqIxwAmX30P2IRNGvKZTC2NAwcbd4=,iv:DwX1Qtx/9EtkWxWASgu4wER0WrUhgmA+S0a50djopaA=,tag:FlSKv8Sie+71OSkqPIR1uA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
