apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-homepage
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MosheAzraf/pi-cluster.git
    targetRevision: main
    path: kubernetes/apps/homepage/
    #enable this when adding secret file
    #plugin:
    #  name: ksops

  destination:
    server: https://kubernetes.default.svc
    namespace: apps-homepage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
