controller:
  replicas: 3

server:
  replicas: 3

repoServer:
  replicas: 3

dex:
  replicas: 2

redis:
  enabled: false

redis-ha:
  enabled: true


configs:
  cm:
    redis.server: argocd-redis-ha-haproxy
