server:
  replicas: 2

repoServer:
  replicas: 2

controller:
  replicas: 2
  extraEnv:
    - name: ARGOCD_CONTROLLER_REPLICAS
      value: "2"

dex:
  replicas: 2

redis-ha:
  enabled: true

configs:
  cm:
    redis.server: argocd-redis-ha-haproxy
