# HA mode
redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

  # ---------- KSOPS ----------
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: sops-age
      secret:
        secretName: sops-age

  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.4.0
      args:
        - mv
        - /usr/local/bin/ksops
        - /custom-tools/ksops
      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools

  env:
    - name: SOPS_AGE_KEY_FILE
      value: /.config/sops/age/keys.txt

  volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/ksops
      subPath: ksops
    - name: sops-age
      mountPath: /.config/sops/age
  # ---------- KSOPS ----------

applicationSet:
  replicas: 2

configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"


#before ksops
# #HA mode
# redis-ha:
#   enabled: true

# controller:
#   replicas: 1

# server:
#   autoscaling:
#     enabled: true
#     minReplicas: 2

# repoServer:
#   autoscaling:
#     enabled: true
#     minReplicas: 2

# applicationSet:
#   replicas: 2

# configs:
#   params:
#     server.insecure: true
