apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.kubernetesingress=true"
      - "--providers.kubernetesingress.allowcrossnamespace=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
