apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-reloader
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: reloader
      targetRevision: 2.2.9
      helm:
        valueFiles:
          - $values/kubernetes/infrastructure/reloader/values.yaml
    - repoURL: https://github.com/MosheAzraf/pi-cluster.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
