apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:BpqGPI4=,iv:lmB+4jZn/P8xMvjgCos0sxgv7fiNyTuYkmIrbzNEo/Q=,tag:xjK+OHtCYbTjMGQSlWVvYg==,type:str]
    admin-password: ENC[AES256_GCM,data:L91Vymc=,iv:CuvR/t71aAY4T6cyn+N0oncMk0ocInEoJKgRCj/ROt8=,tag:IscI7WG71P66opsc9nKV8Q==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU3ovOVU5bkZ2NkRheDRi
            RUlyN0t0UWlibnhOQWFHWTZIdU16R1pHWFZFCmYyQkt5QUUrUFV1UXZtbUhPSUd6
            d1ZaNVJ2MVNsZHdIMXN0Z1BWajR6ZFUKLS0tIDFhbXo1WWpuVnRxV204b3lxMDJT
            V3l3YVE4WHRUS0V3OEE5U1Vacm9tOWsKHdKUAeZ/wLYc/V0gop5iXffyNzN7bPZA
            jcFL9MBACFtrKxs50XS5N7idnr5/BpYc6Msj5uQekStgSNjzEpyw0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T15:43:06Z"
    mac: ENC[AES256_GCM,data:kZAYrmvGj4v6s09D+igv6rBMjo5CH5INMVQEJHA7bUc8L9uFGp2iCA6uOYVxeXOeK1tuC482nzglUKi4Xm6qbraOxrWlGJ/rTVUJfB285dGCsCir3TjKYVlGExm8iyAFW+WO6IbN9nEDY5101TmMtsTR6LQ0nmEqNO806dY41QM=,iv:4V8ixKipffWzevD7K8xUMlvSZOTsgaQwKQ4YaKcZAmg=,tag:s0XgbxK3GjjIrJ8W1GSXlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
