apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:BpqGPI4=,iv:lmB+4jZn/P8xMvjgCos0sxgv7fiNyTuYkmIrbzNEo/Q=,tag:xjK+OHtCYbTjMGQSlWVvYg==,type:str]
    admin-password: ENC[AES256_GCM,data:1pAYK1gdObchhrc5TcKW,iv:wO0mG8MbzCPmV519vcwCaVY/cE98O1hMlBLvTO0hSc4=,tag:vf7gE/Q91QJJao6UebKw6g==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU3ovOVU5bkZ2NkRheDRi
            RUlyN0t0UWlibnhOQWFHWTZIdU16R1pHWFZFCmYyQkt5QUUrUFV1UXZtbUhPSUd6
            d1ZaNVJ2MVNsZHdIMXN0Z1BWajR6ZFUKLS0tIDFhbXo1WWpuVnRxV204b3lxMDJT
            V3l3YVE4WHRUS0V3OEE5U1Vacm9tOWsKHdKUAeZ/wLYc/V0gop5iXffyNzN7bPZA
            jcFL9MBACFtrKxs50XS5N7idnr5/BpYc6Msj5uQekStgSNjzEpyw0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T15:13:50Z"
    mac: ENC[AES256_GCM,data:Hg9ypG0Jl6tGZozrr5MKApqI/0x2aPNE7+7iwuO6g9SVKB5XpOhY+0HhtDwiO1VpXipxo7/E3Ufh3REBqGk8onSiOcvDudJni7g7dBxQ4vh9XSbomgfalmWC6OHbUZA5lHG/RHExHaAZ8UJ0ri5UBiril8N5hhNuX27RWHSLvEc=,iv:YcHWn5lacDStC9je9aALD7yJyopjXAG6ur6BupSRs50=,tag:h0Zv86galEQKU2FwkqepLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
