grafana:
  enabled: true
  replicas: 1

  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password

  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi

  service:
    type: ClusterIP


prometheus:
  prometheusSpec:
    replicas: 2
    retention: 3d
    scrapeInterval: 60s
    evaluationInterval: 60s

    externalLabels:
      cluster: homelab

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi


alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 2


kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

kubeApiServer:
  enabled: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false


defaultRules:
  create: false


prometheusOperator:
  admissionWebhooks:
    enabled: true
