apiVersion: v1
kind: Secret
metadata:
    name: test-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:7NvlO1c=,iv:AfPdoXPliX4tGqRMg5ElPxmlmAUkL7d5Zlp/LzUTRAc=,tag:5DpsDFPYNnyPlWcwIV4LAQ==,type:str]
    password: ENC[AES256_GCM,data:x/qkworGk9fbURs=,iv:VCgtK5KS89qwVUhQ25KIrrqOzNYPkahYlhxBHUVyHF4=,tag:WekSyTcR31u3XvYk3Q4PDg==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkKzlqVnRkc0lTNlNuUFlO
            RzNBOVhLaVpybHFoMGtzS1ROUm1hVlRrYkQwCmsyUktYTkVRZ2ViMFhFbWVCUHR2
            cTBCY24zSFBadmVDcTdWeXZMdm9ueVUKLS0tIFV6T2JJZlJwZi9uRjFyQjFEV1hn
            TEJOQytqNk8vc3RtWHRmWW1YMmd2QWcKS34DAd1TAYvzQOvt1vCTFwyhynKYpCik
            ygi4ZBKDrDZj2qcmgEej6EADssuvJbBiuydXWHagNNtjkmrOqM2puQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:27:24Z"
    mac: ENC[AES256_GCM,data:TCTC/0TQAcECQ5gVwbnENhlajSRk+57nApYnsLVyasJ/9j0XJVc7tNh4BafnUbzyl7044kq6qMMJEaSsKcna4dh687h7wj2hdMMXoGEBN+FYhdhkl5xWLhMEw8VEGacnh0FjjOj0CdE22847ke3+1eL36T7XrpM62lhHUN+ry0w=,iv:nExc5jBdZn0rKm9nvrxFHqlgFJ+H68loiO3YINkVcj8=,tag:6ncyQlIaF11c4u1aVpMI6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
