apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-env
    namespace: pgadmin
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:2f+Z6nH9Dg/ML9tukw7GKbJMkcT3,iv:zpSa+7XZmitbJkDXWtH+44VqnXXhIUvlCJvcKOo6XK8=,tag:0KmnuqPoJ9nYHMXwnp6azA==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:mLLEba4dr3fd,iv:mWodVPy8QC0+/GGwR/kFjI/QDdwBqHcjmYYmMeb3io8=,tag:dXxJG3M+9MZRS7aUGytcYQ==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUXZVR2dKZE1OcVAwNmU0
            c2RVSkN5YnNEaVpFeFJ1NkJlYUEzUDNIV0JJCmdJU25PSWd5MEJvNzlSa0R1U04y
            NFNBT0tWRyt5cENTQzUwaE1NL3VSajQKLS0tIGtLRmFmNHZqT0pndFpydHZoZzIx
            NXZBM0VySnBPTVR1aGZ2VStLWEJXTjgK81Nj7Mp8QEHfdcCDrpi0klfmAJRThxc4
            DUDSU3bR9GJ/BI6tonMkqQYWDtiuUJ4Qb9+8pEdeAGMnb2UWaSfErw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T13:02:48Z"
    mac: ENC[AES256_GCM,data:li+hOKW5LGUDAn2TlWEsh8BfJrbvXXu9pnED3p21e4Xbx16at5jJIVVtj/P8lh864nkj6SWDHPp2CJrpdWT412V2uTj+zcJbEpmjda+O400zgeQIiZz/2cvJcFI09PfimYQLigVijfQeOWXpszLPDgKtyA0Xzhg3K9zJTzDmzWE=,iv:QpIxmvkOsf5U+E54LekA7xhhpDE5XhCBTLffrGNXMVA=,tag:82v8Ax2vpvNoIAvfbsLd1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
