apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding
spec:
  secretName: linkding-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  dnsNames:
    - linkding.home.lab