apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:NV9rbNg=,iv:hQVSfrRk0qn2CK8DLMn1iPWprtta4ovbgKxUgqdt+uY=,tag:wrd1L3tuPsYWelcxvJxriw==,type:str]
    admin-password: ENC[AES256_GCM,data:JOBZM/A=,iv:KJGWB5ronkbWVPpP1fhgAgnAS84YkDGg/+jQnLSCLUg=,tag:hhU8Lj+jU8LiNxG9wEA34w==,type:str]
sops:
    age:
        - recipient: age15jrlaat4v3sjsgkk5lu996uqzv5fdn47m7fqz5zfxklgj05dd59q99pug2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVDRNS2cxR0I3MGtlUEt2
            ZG5STmpWb3BTVks2aDZQYnRYd2dsS2FMY0Q4CnV2K2FhWFlCSGZoQlJZSkh1cU54
            UFpYdGorZlppYWtaYTRMaUhITUdGcWsKLS0tIE1RaW8zQlEvZlR1SVBQS1lhTkVZ
            Z2h2Q0Y3bzF2NThnRVBwVzIreFFEODgK5d1/arkff/ZUubn4cBbAGjTQXaGQLT2d
            mnwFbjaaugiESKY6vQW+IlW+lihDzbyNDeQ5tX0Xdy631GkbexHFOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T00:02:53Z"
    mac: ENC[AES256_GCM,data:h8TEij1FAd2k1rUknwxuxoapZnAXH080ytDhhLfCiXVEQ2WPEPoH88kxt5GCv9/UzM8oSr3CbsVfxvdP/QciMYz5ytHH1o2HsTbBT0sF+c5c8Ex5++ednkwAI5GbpEP85PvYgsiJTw2wDOvTfUTfGiIEzBiTWqnTB5pyyyuDb3o=,iv:OMwnlq7btk9nKk2mTXwvU1+pSh2N/o6uF68tn6Qacdo=,tag:nEWpUP8J86UaStlI1ooL4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
